### ISSUE TITLE
AWSSDK.dll is not found in C:\Program Files (x86)\AWS SDK for .NET\bin\Net45  path

### ISSUE THREAD

**Issue by amanakash** [noahlh/aws-automated-backup-powershell#14]
# AWS SDK Path 
Add-Type -Path "C:\Program Files (x86)\AWS SDK for .NET\bin\Net45\AWSSDK.dll"

There is not any AWSSDK.dll in this path. There are many service specific dll but not this one.

am i missing something ??

**Comment by Hubsun** [comment]
I have the same issue as above.  

Which .dll should we use instead?   Should we use  AWSSDK.EC2.dll  instead?

**Comment by amanakash** [comment]
I have found the solution for above issue: 

AWSSDK.dll is available under below path and it is working fine with this script.

"C:\Program Files (x86)\AWS SDK for .NET\past-releases\version-2\Net45\AWSSDK.dll"

**Comment by Hubsun** [comment]
Thanks so much for sharing!

**Comment by dms2015** [comment]
That fixed all my previous errors.  Thank you so much!  Could you also help with this error I am getting while it is running below?  It is getting a call depth overflow error.

The script failed due to call depth overflow.
At C:\AWS\AWSUtilities.ps1:124 char:9
+         WriteToLog "$function : $exception" -isException $true
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (0:Int32) [], RuntimeException
    + FullyQualifiedErrorId : CallDepthOverflow

**Comment by necarlson** [comment]
I fixed this while implementing support for a custom email server, although forgot to mention it in my commit comment. See pull request #19.
